language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
python:
  - "2.7"
env:
  - KOTTI_TEST_DB_STRING=postgresql://postgres@localhost:5432/blogs_testing
  - KOTTI_TEST_DB_STRING=mysql+oursql://root@localhost:3306/blogs_testing
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - travis_retry pip install -U pip wheel setuptools
  - travis_retry pip install psycopg2 oursql python-coveralls codecov
  - pip install -e . -r https://raw.github.com/Kotti/Kotti/stable/requirements.txt
  - pip install --pre Kotti
  - python setup.py devbefore_script:
  - psql -c 'create database blogs_testing;' -U postgres
  - mysql -e 'create database blogs_testing;'
script: py.test --tb=native --cov=blogs --cov-report=term-missing
